### ISSUE TITLE
Ancestral Allele Annotation Outgroup Error in R 

### ISSUE THREAD

**Issue by asumarli** [Sendrowski/fastDFE#10]
Dear Janek, 

I am attempting to infer the ancestral allele of a vcf using Maximum Likelihood in R. However, I run into an error saying that the specified outgroup is not present in the VCF file. I ran into this issue with my data, and then tried to use your existing *betula* data following the R Reference example. This resulted in the same error. I would greatly appreciate any input you may have into solving this! 

Thank you!

Alex

### example for ancestral allele annotation with outgroups
> ann = fd$Annotator(
  vcf = paste0("all.with_outgroups.subset.10000.vcf.gz"),
  annotations = c(fd$MaximumLikelihoodAncestralAnnotation(
    outgroups = c("ERR2103730"),
    n_ingroups = 10
  )),
  output = "genome.aa.vcf.gz"
)

> fd$Annotator$annotate(ann)

### Error
`INFO:Annotator: Start annotating
INFO:Annotator: Loading VCF file
INFO:Annotator: Loading VCF file
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: The specified outgroups () are not present in the VCF file.
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/alexandrasumarli/miniforge3/envs/fastdfe/lib/python3.12/site-packages/fastdfe/annotation.py", line 4316, in annotate
    self._setup()
  File "/Users/alexandrasumarli/miniforge3/envs/fastdfe/lib/python3.12/site-packages/fastdfe/annotation.py", line 4293, in _setup
    annotation._setup(self)
  File "/Users/alexandrasumarli/miniforge3/envs/fastdfe/lib/python3.12/site-packages/fastdfe/annotation.py", line 2290, in _setup
    super()._setup(handler)
  File "/Users/alexandrasumarli/miniforge3/envs/fastdfe/lib/python3.12/site-packages/fastdfe/annotation.py", line 1815, in _setup
    self._prepare_masks(handler._reader.samples)
  File "/Users/alexandrasumarli/miniforge3/envs/fastdfe/lib/python3.12/site-packages/fastdfe/annotation.py", line 1781, in _prepare_masks
    raise ValueError(f"The specified outgroups ({', '.join(missing)}) are not present in the VCF file.")
ValueError: The specified outgroups () are not present in the VCF file.

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─fd$Annotator$annotate(ann)
 2.   └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
See `reticulate::py_last_error()$r_trace$full_call` for more details.`

**Comment by Sendrowski** [comment]
Dear Alex,

For some reason `c("outgroup_name")` gets converted to a Python string through reticulate, which is the wrong input type. This used to be different. You can use `list("outgroup_name")` instead, which seems to work.

Hope this helps!
Janek

**Comment by asumarli** [comment]
Hi Janek,

Thank you for your quick response! Changing to `list` in R worked.

Now that it is working, I was wondering if there is a formal method for determining `n_ingroups` when inferring the AA with ML? In your documentation, you mention 10 or 15 for datasets with several thousands sites. This has been working for me, but I am just curious if it is worth carrying out a more formal analysis to choose `n_ingroups`.

Best,

Alex

**Comment by Sendrowski** [comment]
Hi Alex,

I don't think `n_ingroups` is very important. The ingroup subsample per site is very representative of the actual ingroup allele frequencies when having `subsample_mode = "probabilistic"`, which is the default option. It's much more important to use at least 2 relatively distinct outgroup individuals, to make sure monomorphic sites are included in the VCF (alternatively you can use the `n_target_sites` argument), and to double-check that most inferred ancestral alleles agree with the ad hoc ancestral allele annotation (one gets notified about the number of mismatches).

Best,
Janek

**Comment by asumarli** [comment]
Hi Janek,

Apologies for the slow response. I just wanted to say thank you for your
help!

Best,

Alex

**Comment by Sendrowski** [comment]
You're welcome!
Janek
