### ISSUE TITLE
install error from pip

### ISSUE THREAD

**Issue by Chenglin20170390** [Sendrowski/fastDFE#4]
Hi  when I type 
`pip install fastdfe`

the error occurs

ERROR: Could not find a version that satisfies the requirement fastdfe
ERROR: No matching distribution found for fastdfe

**Comment by Sendrowski** [comment]
Hi!
Which python version are you using? Due do fastdfe's dependencies only Python 3.10 and 3.11 are supported. Could it be that you are using a different version? I would recommend using a separate conda environment as described in the [docs](https://fastdfe.readthedocs.io/en/latest/reference/Python/installation.html).

**Comment by Chenglin20170390** [comment]
Hi ,my python version iis 3.12.2.  I also follow your instruction for install fstDFE by  creating a separate conda environment as "environment.yml "

`cat environment.yml`
name: fastdfe
channels:
    - defaults
dependencies:
    - python
    - pip
    - pip:
        - fastdfe
`conda env create -f environment.yml`
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.1.1b0 Requires-Python >=3.10,<3.12; 0.1.2b0 Requires-Python >=3.10,<3.12; 0.1.3b0 Requires-Python >=3.10,<3.12; 0.1.4b0 Requires-Python >=3.10,<3.12; 0.1.5b0 Requires-Python >=3.10,<3.12; 0.1.6b0 Requires-Python >=3.10,<3.12; 0.1.7b0 Requires-Python >=3.10,<3.12; 0.1.8b0 Requires-Python >=3.10,<3.12; 1.0.0 Requires-Python >=3.10,<3.12; 1.1.0 Requires-Python >=3.10.0,<3.12; 1.1.1 Requires-Python >=3.10.0,<3.12; 1.1.2 Requires-Python >=3.10.0,<3.12; 1.1.3 Requires-Python >=3.10.0,<3.12; 1.1.4 Requires-Python >=3.10.0,<3.12
ERROR: Could not find a version that satisfies the requirement fastdfe (from versions: none)
ERROR: No matching distribution found for fastdfe

failed

CondaEnvException: Pip failed
`python --version  `
Python 3.12.2

**Comment by Sendrowski** [comment]
I suppose it is still installing python 3.12 as the pip dependencies are added later in a separate step. If you pin the python version to 3.11 or 3.10, it should work. I will update this in the docs:

```yaml
name: fastdfe
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastdfe
```

**Comment by Chenglin20170390** [comment]
> I suppose it is still installing python 3.12 as the pip dependencies are only added later in a separate step. If you restrict the python versions to 3.10 and 3.11, it should work. I will update this in the docs:
> 
> ```yaml
> name: fastdfe
> channels:
>   - defaults
> dependencies:
>   - python>=3.10,<3.12
>   - pip
>   - pip:
>       - fastdfe
> ```

Many thanks for your quickly reply, it's working perfect for this command !!

Best,
Lin
