### ISSUE TITLE
install error from R

### ISSUE THREAD

**Issue by Chenglin20170390** [Sendrowski/fastDFE#5]
HI , I try to install fastDFE from R by typing 
`install_fastdfe()`

ERROR: Ignored the following versions that require a different python version: 0.1.1b0 Requires-Python >=3.10,<3.12; 0.1.2b0 Requires-Python >=3.10,<3.12; 0.1.3b0 Requires-Python >=3.10,<3.12; 0.1.4b0 Requires-Python >=3.10,<3.12; 0.1.5b0 Requires-Python >=3.10,<3.12; 0.1.6b0 Requires-Python >=3.10,<3.12; 0.1.7b0 Requires-Python >=3.10,<3.12; 0.1.8b0 Requires-Python >=3.10,<3.12; 1.0.0 Requires-Python >=3.10,<3.12; 1.1.0 Requires-Python >=3.10.0,<3.12; 1.1.1 Requires-Python >=3.10.0,<3.12; 1.1.2 Requires-Python >=3.10.0,<3.12; 1.1.3 Requires-Python >=3.10.0,<3.12; 1.1.4 Requires-Python >=3.10.0,<3.12
ERROR: Could not find a version that satisfies the requirement fastdfe (from versions: none)
ERROR: No matching distribution found for fastdfe
 Error installing package(s): 'fastdfe'

**Comment by Sendrowski** [comment]
Hi again!
We have the exact same problem as [here](https://github.com/Sendrowski/fastDFE/issues/4). R's reticulate package is using pip behind the scenes to install fastdfe, and pip is using a different Python version. Besides that, if R is not your language of absolute preference, I would recommend using the Python interface.

**Comment by Chenglin20170390** [comment]
Thanks for your quickly reply. I have try to install both fastDFE  in R version on my macbook and in python version on server of my institute based on your instructions, but neither it work.

 I am sorry, I know a little about both R and python.

**Comment by Sendrowski** [comment]
To install fastdfe in R, you can use instead of `fastdfe::install_fastdfe`
```r
reticulate::py_install(
    'fastdfe', 
    method = "conda",
    pip = TRUE, 
    version = version, 
    python_version = '3.11',
    ignore_installed = TRUE
)
```

Hope it helps!

**Comment by Chenglin20170390** [comment]
> ```r
> reticulate::py_install(
>     'fastdfe', 
>     method = "conda",
>     pip = TRUE, 
>     version = version, 
>     python_version = '3.11',
>     ignore_installed = TRUE
> )
> ```

Thanks !!!, you are so kind ! it's working very well for me ! both python and R are working perfect now !

Many thanks for your help!

Best,
Lin
