### ISSUE TITLE
Questions about TargetSiteCounter.

### ISSUE THREAD

**Issue by fatlonggg** [Sendrowski/fastDFE#7]
Dear Janek:
Oh, I did ask some very stupid questions (LOL). When you ask me to try TargetSiteCounter first time, I checked it but find hard to understand, so I passed it. But now, I find that it is exactly the answer for my questions. Thank you for your patience. Now I have some new questions.
1. When I use TargetSiteCounter, fastDFE output a INFO which suggest me to use SNPFiltration. I checked the API of TargetSiteCounter, and found this sentence: "It is recommended to use a SNPFiltration when using this class to avoid biasing the result by monomorphic sites present in the VCF file". Is that means the SNPFiltration will exclude the monomorphic sites? But when I used SNPFiltration alone, I found the monomorphic sites were still kept in the flitered_vcf. Here is my script:
```
import fastdfe as fd
f = fd.Filterer(
    vcf="./myvcf.vcf",
    gff="./mygff.gff",
    output='flitered_vcf.gz',
    filtrations=[fd.SNPFiltration()]
)
f.filter()
```
But, when I used SNPFiltration class inside of the "fd.Parser" when inferring the SFS, I can see that the output spectra indeed has "0.0, 0.0" in the last entry. 
```
import fastdfe as fd
p = fd.Parser(
    n=20,
    vcf="./myvcf.vcf",
    fasta="genoem.fa",
    gff="mygff.gff",
    target_site_counter=fd.TargetSiteCounter(
        n_samples=1000000,
        n_target_sites=fd.Annotation.count_target_sites(
            file="genome.gff",
            contigs=["chr1", "chr2", "chr3"]
        )["chr1"]
    ),
    annotations=[
        fd.DegeneracyAnnotation()
    ],
    filtrations=[
        fd.SNPFiltration(),
        fd.CodingSequenceFiltration()
    ],
    stratifications=[fd.DegeneracyStratification()],
    skip_non_polarized=False,
)
# parse SFS
spectra: fd.Spectra = p.parse()
spectra.to_file(file="./sfs.txt")
```
Are the two usages of SNPFiltration different from each other? What sites did SNPFiltration exclude exactly (sites that all samples are "0|0", or "1|1", all both)?
2. TargetSiteCounter need to assign a value to "n_samples", but the tutorial didn't say much about the rules. What value should I assign to "n_samples"? Is 1,000,000 enough for rice genome? 
3. TargetSiteCounter also need to assign a value to "n_target_sites". I also don't know what value I should assign to it, so I decided to use "fd.Annotation.count_target_sites" as the tutorial. However, my vcf contained the whole genome of rice (12 chromosomes), but the tutorial seems only count one chromosome: 
```
n_target_sites=fd.Annotation.count_target_sites(
            "http://ftp.ensembl.org/pub/release-109/gff3/homo_sapiens/"
            "Homo_sapiens.GRCh38.109.chromosome.21.gff3.gz"
        )['21']
```
Can I count the target sites for the whole genome? How should I write the script? Since the n_target_sites need to assign an integer but fd.Annotation.count_target_sites returns a dictory, I'm confused. 
4. Can fastDFE infer the DFE for differnet types of mutations? For example, can I get the DFE of fixed mutations and segregating mutations respectively?

**Comment by Sendrowski** [comment]
Hey again!

1. The idea is to ignore monomorphic sites present in the VCF when using `TargetSiteCounter`. Looking at the code, however, I don't think it will make a difference since the monomorphic sites parsed from the VCF file are ignored anyway. `SNPFiltration` defaults to checking the [`is_snp`](https://brentp.github.io/cyvcf2/docstrings.html) attribute of the variants when considering **all** individuals in the VCF. It could be that your variants are still marked as SNPs based on the presence of alternative alleles of individuals (like outgroups) that were previously present in the VCF before filtering. If you specify a list of individuals to consider, `SNPFiltration` will explicitly count the number of alleles for a variant in order to determine whether it is monomorphic.
2. `n_samples` corresponds to the number of sites sampled from the fasta file from which the monomorphic neutral and selected counts are extrapolated. `1e6` sites should be sufficient.
3. `n_target_sites` is not very important. You can set it to `1e6`, and check whether the inferred DFE changes for different values, but likely not. In any case it, the value should be significantly higher than the number of polymorphic sites in your SFS. You can also determine it more precisely using a mutation rate estimate together with the number of polymorphic sites.
4. It will be difficult to infer the DFE for fixed mutations as `fastDFE` uses the frequency of alleles segregating in the population. You can, however, infer the DFE for different types of mutations by [stratifying](https://fastdfe.readthedocs.io/en/latest/reference/Python/parser.html#stratifications) the SFS.

I hope this helps
Janek

**Comment by fatlonggg** [comment]
Well, actually, for n_target_sites of TargetSiteCounter, I found that you are right about "the order of magnitude should be correct". I tried different value of n_target_sites, and found that it will decide the number of monomorphic sites in the first entry of SFS. If the order of magnitude change, the DFE will also change. Can I simply use **one** chromosome to determine the number for my VCF, which contain **12** chromosomes, by using fd.Annotation.count_target_sites?  (As I did in my script.). Am I doing right?

**Comment by fatlonggg** [comment]
By the way, when you said "fastDFE uses the frequency of alleles segregating in the population", do you mean fastDFE can only infer the DFE of segregating mutations? How about DFEalpha and fitdadi? Are they also can only infer the DFE of segregating mutations? Do you know any other tools to infer the DFE for fixed mutations?

**Comment by Sendrowski** [comment]
> Well, actually, for n_target_sites of TargetSiteCounter, I found that you are right about "the order of magnitude should be correct". I tried different value of n_target_sites, and found that it will decide the number of monomorphic sites in the first entry of SFS. If the order of magnitude change, the DFE will also change. Can I simply use **one** chromosome to determine the number for my VCF, which contain **12** chromosomes, by using fd.Annotation.count_target_sites? (As I did in my script.). Am I doing right?

If the whole genome was sequenced then you could indeed use `fd.Annotation.count_target_sites` to obtain the number of coding sites (which are output per chromosome). But often times you would exclude called variants for a number of reasons (e.g. low quality), so the actual number of target sites is likely smaller. Do you have mutation rate estimates for your dataset? I think that would be a more reliable way to estimate `n_target_sites`. What numbers did you use and much did the DFE change?

**Comment by Sendrowski** [comment]
> By the way, when you said "fastDFE uses the frequency of alleles segregating in the population", do you mean fastDFE can only infer the DFE of segregating mutations? How about DFEalpha and fitdadi? Are they also can only infer the DFE of segregating mutations? Do you know any other tools to infer the DFE for fixed mutations?

`fastDFE`s precursor, `polyDFE`, uses divergence counts but we decided not to include them for `fastDFE` since they tend to be rather error prone, as informative as they can be.

**Comment by fatlonggg** [comment]
> What numbers did you use and much did the resulting DFE change?
I tried to set the n_target_sites to 1e5, 1e6, 1e7 and 1e8, and found that the result of 1e5 differ a lot from the other values. But except for 1e5, the DFE results of the other numbers have no difference. 

> If the whole genome was sequenced then you could indeed use fd.Annotation.count_target_sites to obtain the number of coding sites (which are output per chromosome).
Are you meaning that fd.Annotation.count_target_sites will count one chromosome, and use the result to represent all chromosome, by assuming that all chromosomes have the same ratio of target sites to chromosome's length? If not, how should I use fd.Annotation.count_target_sites to calculate the fd.Annotation.count_target_sites for all chromosomes?

By the may, I met a new error when inferring the SFS, and I have no idea how to deal with it. I konw that this error shows up maybe because some error in my gff file, but I don't know how to check it. The attached file is the error message. Do you have any suggestions?
[error.txt](https://github.com/user-attachments/files/17265545/error.txt)

**Comment by Sendrowski** [comment]
It is expected that the inferred DFE differs for a very low number of target sites. `1e5` monomorphic sites would imply a very high mutation rate given that you like have a few thousand polymorphic sites, and is thus not very realistic. As long as the DFE stays the same for larger values of `n_target_sites`, you should be fine :)

The error results from the phase not being defined for some of your coding sequences. You could circumvent this by filtering out all entries in your GFF file where phase is `”.”`.

**Comment by fatlonggg** [comment]
Thank you so much. Now I got the ideal results. I don't have further questions for now.

**Comment by Sendrowski** [comment]
Perfect! I will close this for now then
