### ISSUE TITLE
Estimating the proportion of positive selection

### ISSUE THREAD

**Issue by jydu** [Sendrowski/fastDFE#9]
Hi Janek,

I have managed to run fastDFE on a few datasets of my own and I get intriguing results. Parameter p_b is systematically reported to be 0 (while I expect positive selection to be present). More surprisingly, S_b seems to be accurately estimated... how can this parameter be estimated if p_b is 0? I notice that in your example in the documentation, p_b is also found to be zero (with a msg telling not to worry...). On a side note, is there a way to derive the omega_a quantity (reported by PolyDFE) for the estimated parameters?

Many thanks in advance for your help,

Julien.

**Comment by Sendrowski** [comment]
Hi Julien,

p_b is often estimated to be 0 but not always. If p_b is 0 then S_b should vary freely. Did you also look at the bootstraps? You can share your spectra with me so I can take a look.

Do you mean the expected proportion of beneficial non-synonymous substitutions (which we refer to as alpha)? That should be accessible via BaseInference.alpha<https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.base_inference.BaseInference.alpha> or BaseInference.bootstraps.alpha.

Best,
Janek
________________________________
Gönderen: Julien Y. Dutheil ***@***.***>
Gönderildi: Tuesday, October 15, 2024 8:19:53 PM
Kime: Sendrowski/fastDFE ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [Sendrowski/fastDFE] Estimating the proportion of positive selection (Issue #9)


Hi Janek,

I have managed to run fastDFE on a few datasets of my own and I get intriguing results. Parameter p_b is systematically reported to be 0 (while I expect positive selection to be present). More surprisingly, S_b seems to be accurately estimated... how can this parameter be estimated if p_b is 0? I notice that in your example in the documentation, p_b is also found to be zero (with a msg telling not to worry...). On a side note, is there a way to derive the omega_a quantity (reported by PolyDFE) for the estimated parameters?

Many thanks in advance for your help,

Julien.

**Comment by Sendrowski** [comment]
Hi Julien,

`p_b` is often estimated to be 0 but not always. If `p_b` is 0 then `S_b` should vary freely. Did you also look at the bootstraps? You can also share your spectra with me so I can take a look.

Do you mean the expected proportion of beneficial non-synonymous substitutions (which we refer to as alpha)? That should be accessible via [`BaseInference.alpha`](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.base_inference.BaseInference.alpha) or `BaseInference.bootstraps.alpha`.
